#!/bin/sh

# find . -name '*.?pp'

files="
./chapter05/conan_example/src/main.cpp
./chapter05/find_module/dep/include/obscure/obscure.hpp
./chapter05/find_module/dep/src/obscure.cpp
./chapter05/find_module/dep/src/internal.hpp
./chapter05/find_module/dep/src/internal.cpp
./chapter05/find_module/src/main.cpp
./chapter05/external_project/src/main.cpp
./chapter05/fetch_content_example/src/main.cpp
./chapter05/find_package_example/src/main.cpp
./chapter05/vcpkg_example/src/main.cpp
./chapter02/component2/include/framework/components/component2.hpp
./chapter02/component2/src/component2.cpp
./chapter02/simple_example/src/main.cpp
./chapter02/component1/include/framework/components/component1.hpp
./chapter02/component1/src/component1.cpp
./chapter02/component_interface/include/framework/components/component_interface.hpp
./chapter02/driver_app/src/main.cpp
./chapter03/hello_object_lib/include/hello_object/hello_object.hpp
./chapter03/hello_object_lib/src/hello_object.cpp
./chapter03/hello_simple_library_example/include/hello/hello.hpp
./chapter03/hello_simple_library_example/src/internal.hpp
./chapter03/hello_simple_library_example/src/hello.cpp
./chapter03/hello_simple_library_example/src/internal.cpp
./chapter03/hello_header_only/include/hello_header_only/hello_header_only.hpp
./chapter03/hello_world_standalone/src/main.cpp
./chapter03/hello_shared_lib/include/hello/hello.hpp
./chapter03/hello_shared_lib/src/internal.hpp
./chapter03/hello_shared_lib/src/hello.cpp
./chapter03/hello_shared_lib/src/internal.cpp
./chapter03/hello_static_lib/include/hello/hello.hpp
./chapter03/hello_static_lib/src/internal.hpp
./chapter03/hello_static_lib/src/hello.cpp
./chapter03/hello_static_lib/src/internal.cpp
./chapter03/src/main.cpp
./chapter04/ex05_consumer/src/main.cpp
./chapter04/ex01_executable/src/main.cpp
./chapter04/ex02_static/include/chapter4/ex02/lib.hpp
./chapter04/ex02_static/src/lib.cpp
./chapter04/ex06_pack/executable/src/main.cpp
./chapter04/ex06_pack/library/include/chapter4/ex06/lib.hpp
./chapter04/ex06_pack/library/src/lib.cpp
./chapter04/ex07_pack_nsis_standalone/executable/src/main.cpp
./chapter04/ex07_pack_nsis_standalone/library/include/chapter4/ex07/lib.hpp
./chapter04/ex07_pack_nsis_standalone/library/src/lib.cpp
./chapter04/ex05_config_file_package/include/chapter4/ex05/lib.hpp
./chapter04/ex05_config_file_package/src/lib.cpp
./chapter04/ex04_directory/dir2/chapter4_hello.hpp
./chapter10/ex02_external_deps_with_extproject/src/tests.cpp
./chapter10/ex03_simple_qt_app/main.cpp
./chapter10/ex01_external_deps/src/tests.cpp
./chapter10/ex01_external_deps/src/benchmarks.cpp
./chapter11/framework_example/include/hello/hello.hpp
./chapter11/framework_example/src/internal.hpp
./chapter11/framework_example/src/hello.cpp
./chapter11/framework_example/src/internal.cpp
./chapter08/configure_file_example/src/main.cpp
./chapter08/custom_target_dependency_example/src/main.cpp
./chapter08/chaining_custom_commands_example/src/main.cpp
./chapter08/custom_command_example/src/main.cpp
./chapter08/execute_process_example/src/main.cpp
./chapter01/policy_example/src/main.cpp
./chapter01/simple_executable/src/main.cpp
./chapter06/ex01_doxdocgen/include/chapter6/ex01/calculator_interface.hpp
./chapter06/ex01_doxdocgen/include/chapter6/ex01/calculator.hpp
./chapter06/ex01_doxdocgen/src/calculator.cpp
./chapter06/ex01_doxdocgen/src/main.cpp
./chapter06/ex02_doxplantuml/src/main.cpp
./chapter07/test_labels/src/main.cpp
./chapter07/cppcheck_example/src/main.cpp
./chapter07/cpplint_example/src/main.cpp
./chapter07/timeout_example/src/main.cpp
./chapter07/coverage_example/src/coverage_example/coverage_example.cpp
./chapter07/coverage_example/src/coverage_test.cpp
./chapter07/test_discovery_example/src/test.cpp
./chapter07/fixture_example/src/main.cpp
./chapter07/fixture_example/src/server.cpp
./chapter07/custom_build_type/src/coverage_example/coverage_example.cpp
./chapter07/custom_build_type/src/coverage_test.cpp
./chapter07/simple_sanitizer_example/src/main.cpp
./chapter07/clang_tidy_example/src/main.cpp
./chapter07/resource_group_example/src/main.cpp
./chapter07/simple_test/src/main.cpp
./chapter07/pass_fail_criteria/src/main.cpp
./chapter07/iwyu_example/src/main.cpp
./chapter07/lwyu_example/src/main.cpp
./chapter13/ex03_external_cmake_module/src/main.cpp
./chapter13/ex02_envfile_utility/test-executable/test.cpp
./chapter14/precompiled_headers/src/fibonacci.cpp
./chapter14/precompiled_headers/src/pythagoras.cpp
./chapter14/precompiled_headers/src/eratosthenes.cpp
./chapter14/precompiled_headers/src/main.cpp
./chapter14/unity_build_group/src/fibonacci.cpp
./chapter14/unity_build_group/src/pythagoras.cpp
./chapter14/unity_build_group/src/eratosthenes.cpp
./chapter14/unity_build_group/src/main.cpp
./chapter14/unity_build/src/fibonacci.cpp
./chapter14/unity_build/src/eratosthenes.cpp
./chapter14/unity_build/src/main.cpp
./chapter12/check_push_pop/include/hello.hpp
./chapter12/iOS_example/include/hello/hello.hpp
./chapter12/iOS_example/src/internal.hpp
./chapter12/iOS_example/src/hello.cpp
./chapter12/iOS_example/src/internal.cpp
./chapter12/emulator-example/src/main.cpp
./chapter12/android-example/include/hello/hello.hpp
./chapter12/android-example/src/internal.hpp
./chapter12/android-example/src/hello.cpp
./chapter12/android-example/src/internal.cpp
"

bigest_files="
./chapter10/ex03_simple_qt_app/main.cpp
./chapter04/ex07_pack_nsis_standalone/executable/src/main.cpp
./chapter04/ex02_static/include/chapter4/ex02/lib.hpp
./chapter04/ex05_config_file_package/include/chapter4/ex05/lib.hpp
./chapter04/ex06_pack/library/include/chapter4/ex06/lib.hpp
./chapter04/ex07_pack_nsis_standalone/library/include/chapter4/ex07/lib.hpp
./chapter07/coverage_example/src/coverage_example/coverage_example.cpp
./chapter07/custom_build_type/src/coverage_example/coverage_example.cpp
./chapter10/ex01_external_deps/src/benchmarks.cpp
./chapter10/ex02_external_deps_with_extproject/src/tests.cpp
./chapter02/component1/src/component1.cpp
./chapter06/ex01_doxdocgen/src/main.cpp
./chapter02/component2/src/component2.cpp
./chapter06/ex02_doxplantuml/src/main.cpp
./chapter06/ex01_doxdocgen/src/calculator.cpp
./chapter02/component_interface/include/framework/components/component_interface.hpp
./chapter02/component1/include/framework/components/component1.hpp
./chapter02/component2/include/framework/components/component2.hpp
./chapter05/find_package_example/src/main.cpp
./chapter02/driver_app/src/main.cpp
./chapter06/ex01_doxdocgen/include/chapter6/ex01/calculator_interface.hpp
./chapter06/ex01_doxdocgen/include/chapter6/ex01/calculator.hpp
"

for f in $files;
do
  ### clang-format $f | diff -u $f -
  clang-format -i $f
  ## egrep --color '\*\w+' $f
  # wc -l $f
done

